- src/com/uwsoft/editor/gdx/ui/dialogs/CustomVariablesDialog.java
- src/com/uwsoft/editor/gdx/ui/properties/BasicItemProperties.java
The new Custom Variable Dialog designed using VisUI.  Should allow for easier reading on different screen resolutions, as the list of variables are no longer boxed to small dimensions on lower resolutions.
> New custom var dialog

- .gitignore
- src/com/uwsoft/editor/gdx/actors/SelectionRectangle.java
- src/com/uwsoft/editor/gdx/sandbox/ItemSelector.java
- src/com/uwsoft/editor/gdx/ui/UIToolBox.java
- extended alignment functionality by center horizontally/vertically (relative to the broadest/highest item of the current selection)
- added git-ignored "local" directory
> extended alignment functionality

- src/com/uwsoft/editor/gdx/sandbox/Sandbox.java
- src/com/uwsoft/editor/gdx/ui/UILightBox.java
- src/com/uwsoft/editor/gdx/ui/properties/BasicItemProperties.java
- colorpicker (tint, ambience) picks respective current color initially
- fixed bug: ambience color change affecting scene visually although affection is disabled
> minor changes according to the color pickers 

- src/com/uwsoft/editor/gdx/ui/LibraryList.java
Added search box in Library items tab
> Search box library items

- src/com/uwsoft/editor/gdx/actors/SelectionRectangle.java
- src/com/uwsoft/editor/gdx/sandbox/ItemSelector.java
- src/com/uwsoft/editor/gdx/ui/UIToolBox.java
- added edge alignment (left, right, top, bottom); Note: buttons need to be modified visually
- refactored older code (and fixed some alignment bugs)
> extended alignment tool box

- src/com/uwsoft/editor/gdx/sandbox/ItemSelector.java
- src/com/uwsoft/editor/gdx/ui/UIToolBox.java
Added Tooltip messages for UiToolBox.
> Tooltip messages

- src/com/uwsoft/editor/data/manager/DataManager.java
> fixed getting list of images of atlas file

- src/com/uwsoft/editor/controller/commands/CreateItemCommand.java
- src/com/uwsoft/editor/factory/ItemFactory.java
- src/com/uwsoft/editor/view/ItemControlMediator.java
Merge branch 'ashley-mvc' of https://github.com/gevorg-kopalyan/overlap2d into mvc-ashley
Conflicts:
src/com/uwsoft/editor/view/stage/tools/TransformTool.java
> Z-index for new item - issue #77

- build.gradle
- settings.gradle
- src/com/uwsoft/editor/view/stage/Sandbox.java
- src/com/uwsoft/editor/view/ui/properties/panels/UISpineAnimationItemPropertiesMediator.java
External Item Type Injection Mechanism for future plugins
> removed spine from commons, and added as an external component

- src/com/uwsoft/editor/view/Overlap2DMenuBar.java
From command bar the file/Exit submenu is not working 
the proposed patch in this pull request fixes the problem
> File / Exit subcommand inactive

- assets/style/uiskin.json
- src/com/uwsoft/editor/Main.java
> uiskin.json ==> add FileChooserStyle, ColorPickerStyle, fixed resource

- src/com/uwsoft/editor/data/manager/PreferencesManager.java
ignore recent list when project file is not existed
> ignore recent list when project file is not existed

- src/com/uwsoft/editor/view/stage/SandboxMediator.java
Now you can zoom by scrolling the mouse and holing the Ctrl (or command)
> scroll zoom with control pressed

- src/com/uwsoft/editor/utils/runtime/EntityUtils.java
- src/com/uwsoft/editor/view/ui/box/UIItemsTreeBox.java
- src/com/uwsoft/editor/view/ui/box/UIItemsTreeBoxMediator.java
> Itemstree bidir change

- src/com/uwsoft/editor/controller/BootstrapCommand.java
- src/com/uwsoft/editor/controller/commands/ItemTransformCommand.java
- src/com/uwsoft/editor/utils/TransformCommandBuilder.java
- src/com/uwsoft/editor/view/stage/Sandbox.java
- src/com/uwsoft/editor/view/stage/tools/TransformTool.java
> - transform actions now undo-/redoable

- src/com/uwsoft/editor/controller/commands/component/UpdateLightDataCommand.java
- src/com/uwsoft/editor/view/ui/properties/panels/UILightItemProperties.java
- src/com/uwsoft/editor/view/ui/properties/panels/UILightItemPropertiesMediator.java
Added Light Softness length support
> Light Softness Length

- src/com/uwsoft/editor/utils/EntityBounds.java
> aligning of scaled items works properly now

- src/com/uwsoft/editor/view/stage/ItemSelector.java
- src/com/uwsoft/editor/view/stage/tools/SelectionTool.java
fixes sub issue from #158 
but it's still possible to select hidden items over the item tree box or the layer box
> hidden items not selectable on canvas anymore (via direct mouse click)

- src/com/uwsoft/editor/controller/commands/ConvertToCompositeCommand.java
> fixing composite conversion bug

- src/com/uwsoft/editor/view/ui/box/UILayerBox.java
- src/com/uwsoft/editor/view/ui/box/UILayerBoxMediator.java
> some refactoring (HIDE_LAYER & LOCK_LAYER event names were confusing)

- src/com/uwsoft/editor/data/vo/ProjectVO.java
- src/com/uwsoft/editor/proxy/ProjectManager.java
- src/com/uwsoft/editor/proxy/ResolutionManager.java
- src/com/uwsoft/editor/view/ui/dialog/ExportSettingsDialog.java
- src/com/uwsoft/editor/view/ui/dialog/ExportSettingsDialogMediator.java
Updated the required files (export dialog + resolutionmanager) to add the duplicatePadding setting to TexturePacker exports
Fixes #226
> Add duplicatePadding to TexturePacker settings (fixes #226)

- src/com/uwsoft/editor/proxy/FontManager.java
Provide there paths and then check the folder exist first.
Fix #242
> Check font folder first

- .travis.yml
- build.gradle
- test/com/LibgdxRule.java
- test/com/commons/O2DDialogTest.java
- test/com/runner/LibgdxRunner.java
- test/com/runner/NeedGL.java
- test/com/runner/exception/LibgdxInitException.java
- test/com/runner/exception/TimeoutException.java
- test/com/runner/util/Condition.java
- test/com/runner/util/ConditionWaiter.java
- test/com/uwsoft/editor/data/manager/PreferencesManagerTest.java
- test/com/uwsoft/editor/proxy/CommandManagerTest.java
- test/com/uwsoft/editor/proxy/FontManagerTest.java
- test/com/uwsoft/editor/proxy/PluginManagerTest.java
- test/com/uwsoft/editor/proxy/ProjectManagerTest.java
- test/com/uwsoft/editor/utils/AppConfigTest.java
I add a new runner `LibgdxRunner`..
This runner provides a libgdx env (for example, Gdx.files). If you use annotation `NeedGL`, you can get Gdx.gl in test.
And I add a new config for xvfb to make sure travis works well with our testes.
> Enhance unit test

- src/com/uwsoft/editor/proxy/ProjectManager.java
- src/com/uwsoft/editor/view/menu/Overlap2DMenuBar.java
Added file path to project name in recent projects menu sub bar. 
P.S. Sorry if i did something wrong, this is my first contribution :(
> File path in recent menu bar #247 

- overlap2d-common-api/build.gradle
- overlap2d/test/java/com/runner/LibgdxRunner.java
- overlap2d/test/java/com/runner/util/ConditionWaiter.java
- overlap2d/test/java/com/runner/util/UIHelper.java
- overlap2d/test/java/com/uwsoft/editor/utils/runtime/ComponentClonerTest.java
- overlap2d/test/java/com/uwsoft/editor/view/ui/box/UIResolutionBoxTest.java
- overlap2d/test/java/com/uwsoft/editor/view/ui/dialog/CustomVariablesDialogMediatorTest.java
- overlap2d/test/java/com/uwsoft/editor/view/ui/dialog/ExportSettingsDialogTest.java
- overlap2d/test/java/com/uwsoft/editor/view/ui/dialog/ImportDialogMediatorTest.java
- overlap2d/test/java/com/uwsoft/editor/view/ui/dialog/ImportDialogTest.java
- overlap2d/test/java/com/uwsoft/editor/view/ui/dialog/NewProjectDialogTest.java
- overlap2d/test/java/com/uwsoft/editor/view/ui/widget/O2DLogoTest.java
1.Add more test
2.modular is available in maven repo, so I remove the jar file.
> Enhance test

- overlap2d/src/com/uwsoft/editor/data/manager/PreferencesManager.java
- overlap2d/src/com/uwsoft/editor/proxy/PluginManager.java
- overlap2d/src/com/uwsoft/editor/proxy/ProjectManager.java
- overlap2d/src/com/uwsoft/editor/proxy/ResolutionManager.java
- overlap2d/src/com/uwsoft/editor/proxy/ResourceManager.java
- overlap2d/src/com/uwsoft/editor/proxy/SceneDataManager.java
- overlap2d/src/com/uwsoft/editor/view/ui/box/UIResolutionBoxMediator.java
- overlap2d/src/com/uwsoft/editor/view/ui/dialog/ImportDialogMediator.java
- overlap2d/src/com/uwsoft/editor/view/ui/dialog/NewProjectDialogMediator.java
- overlap2d/test/java/com/uwsoft/editor/proxy/ProjectManagerTest.java
Mainly removed all logic related to old workspaces, now projects are loaded by full path
> #266 fix, and changes in project loading structure

- build.gradle
- overlap2d-common-api/build.gradle
- overlap2d-common-api/src/com/commons/O2DDialog.java
- overlap2d-common-api/src/com/commons/color/ColorChannelWidget.java
- overlap2d-common-api/src/com/commons/color/ColorInputField.java
- overlap2d-common-api/src/com/commons/color/ColorPickerText.java
- overlap2d-common-api/src/com/commons/color/CustomColorPicker.java
- overlap2d/assets/style/uiskin.json
- overlap2d/src/com/uwsoft/editor/event/NumberSelectorOverlapListener.java
- overlap2d/src/com/uwsoft/editor/utils/StandardWidgetsFactory.java
- overlap2d/src/com/uwsoft/editor/view/menu/Overlap2DMenuBarMediator.java
- overlap2d/src/com/uwsoft/editor/view/ui/box/UIGridBox.java
- overlap2d/src/com/uwsoft/editor/view/ui/dialog/EditSpriteAnimationDialog.java
- overlap2d/src/com/uwsoft/editor/view/ui/dialog/ImportDialogMediator.java
- overlap2d/src/com/uwsoft/editor/view/ui/dialog/NewProjectDialog.java
- overlap2d/src/com/uwsoft/editor/view/ui/dialog/PhysicsEditorDialog.java
- overlap2d/src/com/uwsoft/editor/view/ui/properties/UIItemProperties.java
- overlap2d/src/com/uwsoft/editor/view/ui/properties/panels/UILabelItemProperties.java
- overlap2d/src/com/uwsoft/editor/view/ui/properties/panels/UILightItemProperties.java
- overlap2d/src/com/uwsoft/editor/view/ui/properties/panels/UIPhysicsProperties.java
- overlap2d/src/com/uwsoft/editor/view/ui/properties/panels/UISceneProperties.java
- overlap2d/src/com/uwsoft/editor/view/ui/properties/panels/UISpriteAnimationItemProperties.java
- overlap2d/src/com/uwsoft/editor/view/ui/validator/NewProjectDialogValidator.java
- overlap2d/src/com/uwsoft/editor/view/ui/widget/InputFileWidget.java
- overlap2d/test/java/com/commons/O2DDialogTest.java
- overlap2d/test/java/com/uwsoft/editor/event/NumberSelectorOverlapListenerTest.java
- overlap2d/test/java/com/uwsoft/editor/view/ui/validator/NewProjectDialogValidatorTest.java
> Epic upgrade to libGDX 1.7.1 with vis ui version change consequences.

- overlap2d/src/com/uwsoft/editor/controller/commands/component/UpdateLightDataCommand.java
- overlap2d/src/com/uwsoft/editor/view/ui/box/UIMultiPropertyBox.java
- overlap2d/src/com/uwsoft/editor/view/ui/properties/panels/UILightItemProperties.java
- overlap2d/src/com/uwsoft/editor/view/ui/properties/panels/UILightItemPropertiesMediator.java
Rotation still is in no effect nor there is any way to use shortcuts and mouse scroll, but cone light has now a direction field
> Fixing #320

- overlap2d/src/com/uwsoft/editor/view/ui/properties/panels/UIPolygonComponentPropertiesMediator.java
This fix consists of 2 parts - check overlap2d-libgdx-runtime for the other part.
> Editor part of the fix - see issue 345

- overlap2d/src/com/uwsoft/editor/controller/commands/PasteItemsCommand.java
- overlap2d/src/com/uwsoft/editor/factory/ItemFactory.java
> fixes #337

- overlap2d/src/com/uwsoft/editor/proxy/ProjectManager.java
- overlap2d/src/com/uwsoft/editor/view/menu/Overlap2DMenuBarMediator.java
> fixes #327

- overlap2d/src/com/uwsoft/editor/view/stage/tools/TransformTool.java
- overlap2d/src/com/uwsoft/editor/view/ui/followers/BasicFollower.java
Fixed Problem where:
a) Follower for Composite Items did not fit the size of the content of the composite item (See BasicFollower.java)
b) Problem that was posed by the fix on BasicFollower.java, where scaling the composite item showed strange behaviour (See TransformTool.java)
> Issue 351 follower size

- overlap2d/src/com/uwsoft/editor/utils/EntityBounds.java
- overlap2d/src/com/uwsoft/editor/view/stage/input/SandboxInputAdapter.java
- overlap2d/src/com/uwsoft/editor/view/stage/tools/SelectionTool.java
> fixes issue #372

- overlap2d/src/com/uwsoft/editor/proxy/ProjectManager.java
> fixes issue_307

- overlap2d/src/com/uwsoft/editor/factory/ItemFactory.java
particle effect icon and light icon sizes correction (now icon sizes independent of pixelToWorld value)
> particle effect icon and light icon sizes correction

- overlap2d/src/com/uwsoft/editor/proxy/ProjectManager.java
Fixed this issue. Noted that passing strings around is not ideal.
> Fixed issue with deleting 9 patch files.

- overlap2d/src/com/uwsoft/editor/controller/BootstrapCommand.java
- overlap2d/src/com/uwsoft/editor/controller/commands/NonRevertibleCommand.java
- overlap2d/src/com/uwsoft/editor/controller/commands/resource/DeleteImageResource.java
- overlap2d/src/com/uwsoft/editor/controller/commands/resource/DeleteLibraryItem.java
- overlap2d/src/com/uwsoft/editor/controller/commands/resource/DeleteParticleEffect.java
- overlap2d/src/com/uwsoft/editor/controller/commands/resource/DeleteSpineAnimation.java
- overlap2d/src/com/uwsoft/editor/controller/commands/resource/DeleteSpriteAnimation.java
- overlap2d/src/com/uwsoft/editor/controller/commands/resource/DeleteSpriterAnimation.java
- overlap2d/src/com/uwsoft/editor/proxy/ProjectManager.java
- overlap2d/src/com/uwsoft/editor/utils/runtime/EntityUtils.java
- overlap2d/src/com/uwsoft/editor/view/ui/UIDropDownMenuMediator.java
- overlap2d/src/com/uwsoft/editor/view/ui/box/UIResourcesBoxMediator.java
- overlap2d/src/com/uwsoft/editor/view/ui/box/resourcespanel/UIAnimationsTabMediator.java
- overlap2d/src/com/uwsoft/editor/view/ui/box/resourcespanel/UIParticleEffectsTabMediator.java
- overlap2d/src/com/uwsoft/editor/view/ui/box/resourcespanel/draggable/box/SpineResource.java
- overlap2d/src/com/uwsoft/editor/view/ui/box/resourcespanel/draggable/box/SpriteResource.java
- overlap2d/src/com/uwsoft/editor/view/ui/box/resourcespanel/draggable/box/SpriterResource.java
- overlap2d/src/com/uwsoft/editor/view/ui/box/resourcespanel/draggable/list/ParticleEffectResource.java
adds animations(spine animation, spirte animation and spriter animation) and particle effect delete supprot
bugfix - removing image resource from resource panel all library items and entities that contain that resource get removed
> animations and particle delete support, bugfix
